Repository stratum-mining/stratum, pull requests merged in 2024-08, with the labels that each got.

#1103 update `roles/Cargo.lock`
  roles/Cargo.lock
Labels: ci/cd, clean-up

#1039 `pre-push` githook for fmt only + remove `act`
  .githooks/pre-push
  .github/workflows/release-libs.yaml
  .gitignore
  scripts/clippy-fmt-and-test.sh
  scripts/sv2-header-check.sh
Labels: ci/cd

#1097 Move`PoolSv2` lib code out of `main.rs`
  roles/pool/src/lib/mining_pool/mod.rs
  roles/pool/src/lib/mod.rs
  roles/pool/src/main.rs
Labels: ready-to-be-merged
