Repository stratum-mining/stratum, pull requests merged in 2025-01, with the labels that each got.

#1295 fix: clarify logging
  roles/translator/src/lib/mod.rs
Labels: ready-to-be-merged

#1318 simplify `[package.metadata.docs.rs]` on `protocols` crates
  protocols/v2/binary-sv2/binary-sv2/Cargo.toml
  protocols/v2/binary-sv2/no-serde-sv2/codec/Cargo.toml
  protocols/v2/binary-sv2/no-serde-sv2/derive_codec/Cargo.toml
  protocols/v2/binary-sv2/serde-sv2/Cargo.toml
  protocols/v2/codec-sv2/Cargo.toml
  protocols/v2/const-sv2/Cargo.toml
  protocols/v2/framing-sv2/Cargo.toml
  protocols/v2/noise-sv2/Cargo.toml
  protocols/v2/roles-logic-sv2/Cargo.toml
  protocols/v2/subprotocols/common-messages/Cargo.toml
  protocols/v2/subprotocols/job-declaration/Cargo.toml
  protocols/v2/subprotocols/mining/Cargo.toml
  protocols/v2/subprotocols/template-distribution/Cargo.toml
  protocols/v2/sv2-ffi/Cargo.toml
  utils/buffer/Cargo.toml
Labels: ci/cd

#1297 Integration tests cleanup
  .github/workflows/integration-tests.yaml
  .github/workflows/test.yaml
  roles/Cargo.lock
  roles/jd-client/src/lib/mod.rs
  roles/jd-server/src/lib/mod.rs
  roles/tests-integration/Cargo.toml
  roles/tests-integration/README.md
  roles/tests-integration/lib/mod.rs
  roles/tests-integration/lib/sniffer.rs
  roles/tests-integration/lib/template_provider.rs
  roles/tests-integration/lib/utils.rs
  roles/tests-integration/tests/common/mod.rs
  roles/tests-integration/tests/pool_integration.rs
  roles/tests-integration/tests/sniffer_integration.rs
  roles/tests-integration/tests/translator_integration.rs
Labels: ci/cd, integration-tests

#1238 Propose an implementation of `noise_sv2` with optional `no_std`
  protocols/v2/noise-sv2/Cargo.toml
  protocols/v2/noise-sv2/README.md
  protocols/v2/noise-sv2/examples/handshake.rs
  protocols/v2/noise-sv2/src/cipher_state.rs
  protocols/v2/noise-sv2/src/error.rs
  protocols/v2/noise-sv2/src/handshake.rs
  protocols/v2/noise-sv2/src/initiator.rs
  protocols/v2/noise-sv2/src/lib.rs
  protocols/v2/noise-sv2/src/responder.rs
  protocols/v2/noise-sv2/src/signature_message.rs
  protocols/v2/noise-sv2/src/test.rs
Labels: ready-to-be-merged

#1321 fix jdc sigterm signalling issue
  roles/jd-client/src/lib/mod.rs
Labels: roles, ready-to-be-merged

#1319 fix sigterm issue with translator sv2
  roles/translator/src/lib/mod.rs
Labels: roles, ready-to-be-merged

#1263 docs `roles_logic_sv2`
  protocols/v2/roles-logic-sv2/Cargo.toml
  protocols/v2/roles-logic-sv2/README.md
  protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
  protocols/v2/roles-logic-sv2/src/channel_logic/mod.rs
  protocols/v2/roles-logic-sv2/src/channel_logic/proxy_group_channel.rs
  protocols/v2/roles-logic-sv2/src/common_properties.rs
  protocols/v2/roles-logic-sv2/src/errors.rs
  protocols/v2/roles-logic-sv2/src/handlers/common.rs
  protocols/v2/roles-logic-sv2/src/handlers/job_declaration.rs
  protocols/v2/roles-logic-sv2/src/handlers/mining.rs
  protocols/v2/roles-logic-sv2/src/handlers/mod.rs
  protocols/v2/roles-logic-sv2/src/handlers/template_distribution.rs
  protocols/v2/roles-logic-sv2/src/job_creator.rs
  protocols/v2/roles-logic-sv2/src/job_dispatcher.rs
  protocols/v2/roles-logic-sv2/src/lib.rs
  protocols/v2/roles-logic-sv2/src/parsers.rs
  protocols/v2/roles-logic-sv2/src/routing_logic.rs
  protocols/v2/roles-logic-sv2/src/selectors.rs
  protocols/v2/roles-logic-sv2/src/utils.rs
Labels: ready-to-be-merged

#1341 `Sniffer` messages cleaner
  roles/tests-integration/lib/sniffer.rs
  roles/tests-integration/tests/pool_integration.rs
  roles/tests-integration/tests/sniffer_integration.rs
Labels: integration-tests, ready-to-be-merged

#1339 `InterceptMessage` cleanup
  roles/tests-integration/lib/sniffer.rs
  roles/tests-integration/tests/sniffer_integration.rs
Labels: ready-to-be-merged

#1357 Remove benches execution from CI
  .github/workflows/run-and-track-benchmarks-on-main.yaml
  .github/workflows/run-benchmarks.yaml
  .github/workflows/track-benchmarks.yaml
Labels: ci/cd

#1359 Integration tests avoid tmp dir
  .gitignore
  roles/tests-integration/README.md
  roles/tests-integration/lib/template_provider.rs
Labels: integration-tests, ready-to-be-merged

#1363 remove MG `standard-coverage-test`
  .github/workflows/mg.yaml
  test/message-generator/test/standard-coverage-test/standard-coverage-test.json
  test/message-generator/test/standard-coverage-test/standard-coverage-test.sh
Labels: ready-to-be-merged

#1340 `integration_tests_sv2` docs cleanup
  roles/tests-integration/lib/sniffer.rs
  roles/tests-integration/tests/sniffer_integration.rs
Labels: ready-to-be-merged

#1378 Add retry logic to ensure the pool waits and connect to TP
  roles/pool/src/lib/template_receiver/mod.rs
Labels: bug, refactor, roles, ready-to-be-merged

#1352 Handle unwrap when shutting down JDC server
  benches/Cargo.toml
  examples/ping-pong-with-noise/Cargo.toml
  examples/template-provider-test/Cargo.toml
  protocols/fuzz-tests/Cargo.toml
  protocols/v1/Cargo.toml
  protocols/v2/binary-sv2/binary-sv2/Cargo.toml
  protocols/v2/binary-sv2/no-serde-sv2/codec/Cargo.toml
  protocols/v2/binary-sv2/no-serde-sv2/derive_codec/Cargo.toml
  protocols/v2/binary-sv2/serde-sv2/Cargo.toml
  protocols/v2/codec-sv2/Cargo.toml
  protocols/v2/framing-sv2/Cargo.toml
  protocols/v2/noise-sv2/Cargo.toml
  protocols/v2/roles-logic-sv2/Cargo.toml
  protocols/v2/roles-logic-sv2/src/errors.rs
  protocols/v2/subprotocols/common-messages/Cargo.toml
  protocols/v2/subprotocols/job-declaration/Cargo.toml
  protocols/v2/subprotocols/mining/Cargo.toml
  protocols/v2/subprotocols/template-distribution/Cargo.toml
  protocols/v2/sv2-ffi/Cargo.toml
  roles/Cargo.lock
  roles/jd-client/Cargo.toml
  roles/jd-client/src/lib/downstream.rs
  roles/jd-client/src/lib/mod.rs
  roles/jd-server/Cargo.toml
  roles/mining-proxy/Cargo.toml
  roles/pool/Cargo.toml
  roles/roles-utils/network-helpers/Cargo.toml
  roles/roles-utils/rpc/Cargo.toml
  roles/test-utils/mining-device/Cargo.toml
  roles/translator/Cargo.toml
  utils/message-generator/Cargo.toml
Labels: refactor, roles, ready-to-be-merged

#1391 remove benches workflow from CI
  .github/workflows/fork_pr_benchmark_closed.yaml
Labels: ci/cd, ready-to-be-merged

#1405 guix cleanup
  examples/interop-cpp-no-cargo/README.md
  examples/interop-cpp-no-cargo/guix-build/build.sh
  examples/interop-cpp-no-cargo/guix-build/example.scm
  examples/interop-cpp-no-cargo/guix-build/in_container_build.sh
  examples/interop-cpp-no-cargo/run-with-guix-build.sh
  examples/interop-cpp/README.md
  examples/interop-cpp/template-provider/example-of-guix-build/.gitignore
  examples/interop-cpp/template-provider/example-of-guix-build/build.sh
  examples/interop-cpp/template-provider/example-of-guix-build/example.scm
  examples/interop-cpp/template-provider/example-of-guix-build/quickcheck/Cargo.toml
  examples/interop-cpp/template-provider/example-of-guix-build/quickcheck/src/lib.rs
  examples/interop-cpp/template-provider/example-of-guix-build/quickcheck_macros/Cargo.toml
  examples/interop-cpp/template-provider/example-of-guix-build/quickcheck_macros/src/lib.rs
  examples/interop-cpp/template-provider/in_container_build.sh
  test/interop.cpp
Labels: ready-to-be-merged

#1406 cleanup `sv2-proxy` example
  examples/sv2-proxy/pool-config.toml
  examples/sv2-proxy/proxy-config.toml
  examples/sv2-proxy/run.sh
Labels: ready-to-be-merged

#1396 Braiins/cross testing
  protocols/v2/roles-logic-sv2/Cargo.toml
  protocols/v2/roles-logic-sv2/src/parsers.rs
  protocols/v2/roles-logic-sv2/src/utils.rs
  protocols/v2/subprotocols/mining/src/new_mining_job.rs
Labels: ready-to-be-merged

#1422 point MG crate to crate.io, than using protocol relative path
  utils/message-generator/Cargo.toml
Labels: message-generator, ready-to-be-merged

#1007 Refactor ping pong encrypted example
  .github/workflows/test.yaml
  examples/ping-pong-encrypted/Cargo.toml
  examples/ping-pong-encrypted/README.md
  examples/ping-pong-encrypted/src/client.rs
  examples/ping-pong-encrypted/src/error.rs
  examples/ping-pong-encrypted/src/main.rs
  examples/ping-pong-encrypted/src/messages.rs
  examples/ping-pong-encrypted/src/server.rs
  examples/ping-pong-with-noise/Cargo.toml
  examples/ping-pong-with-noise/README.md
  examples/ping-pong-with-noise/src/main.rs
  examples/ping-pong-with-noise/src/messages.rs
  examples/ping-pong-with-noise/src/node.rs
Labels: ready-to-be-merged
