Repository stratum-mining/stratum, pull requests merged in 2025-02, with the labels that each got.

#1360 Add jds-do-not-fail-on-jdc-shutdown integration test
  .github/workflows/mg.yaml
  roles/jd-client/src/lib/mod.rs
  roles/tests-integration/tests/jd_integration.rs
  roles/translator/src/lib/mod.rs
  test/config/jds-do-not-panic-if-jdc-close-connection/jds-config.toml
  test/message-generator/mock/job-declarator-mock-for-jds-do-not-panic-on-close-connection.json
  test/message-generator/test/jds-do-not-panic-if-jdc-close-connection/jds-do-not-panic-if-jdc-close-connection.json
  test/message-generator/test/jds-do-not-panic-if-jdc-close-connection/jds-do-not-panic-if-jdc-close-connection.sh
Labels: ready-to-be-merged

#1427 remove shutdown notification from downstream disconnect
  roles/translator/src/lib/mod.rs
Labels: ready-to-be-merged

#1424 remove async std from translator
  roles/Cargo.lock
  roles/translator/Cargo.toml
  roles/translator/src/lib/downstream_sv1/downstream.rs
  roles/translator/src/lib/mod.rs
  roles/translator/src/lib/upstream_sv2/diff_management.rs
  roles/translator/src/lib/upstream_sv2/upstream.rs
Labels: translator proxy, refactor, roles, ready-to-be-merged

#1423 remove async-std from mining-device-sv1
  roles/Cargo.lock
  roles/test-utils/mining-device-sv1/Cargo.toml
  roles/test-utils/mining-device-sv1/src/client.rs
  roles/test-utils/mining-device-sv1/src/main.rs
Labels: refactor, cpu miner, roles-utils, roles, ready-to-be-merged

#1482 Remove reject auth test from MG and its footprint
  .github/workflows/mg.yaml
  roles/pool/Cargo.toml
  roles/pool/src/lib/mining_pool/message_handler.rs
  test/message-generator/test/pool-sri-test-reject-auth/pool-sri-test-reject-auth.json
  test/message-generator/test/pool-sri-test-reject-auth/pool-sri-test-reject-auth.sh
Labels: ready-to-be-merged

#1442 Rename `pool_signature` field of `channel_factory` into `additional_coinbase_script_data`, and change the type from `String` to `Vec<u8>`
  protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
  protocols/v2/roles-logic-sv2/src/job_creator.rs
  protocols/v2/roles-logic-sv2/src/job_dispatcher.rs
  roles/jd-client/src/lib/downstream.rs
  roles/jd-client/src/lib/upstream_sv2/upstream.rs
  roles/mining-proxy/src/lib/upstream_mining.rs
  roles/pool/src/lib/mining_pool/mod.rs
  roles/translator/src/lib/proxy/bridge.rs
Labels: refactor, protocols, roles-logic-sv2

#1502 Fix binary sv2 proc macro
  protocols/v2/binary-sv2/derive_codec/src/lib.rs
Labels: ready-to-be-merged

#1499 remove env-filter
  roles/Cargo.lock
  roles/tests-integration/Cargo.toml
  roles/tests-integration/lib/mod.rs
Labels: ready-to-be-merged
