Repository stratum-mining/stratum, pull requests merged in 2025-03, with the labels that each got.

#1492 Use stable rust in `clippy` check and move to a shell script
  .github/workflows/clippy-lint.yaml
  common/src/url.rs
  protocols/v1/examples/client_and_server.rs
  protocols/v1/src/error.rs
  protocols/v1/src/methods/client_to_server.rs
  protocols/v1/src/methods/mod.rs
  protocols/v1/src/methods/server_to_client.rs
  protocols/v1/src/utils.rs
  protocols/v2/binary-sv2/codec/src/codec/decodable.rs
  protocols/v2/binary-sv2/codec/src/codec/encodable.rs
  protocols/v2/binary-sv2/codec/src/codec/impls.rs
  protocols/v2/binary-sv2/codec/src/datatypes/non_copy_data_types/inner.rs
  protocols/v2/binary-sv2/codec/src/datatypes/non_copy_data_types/mod.rs
  protocols/v2/binary-sv2/codec/src/datatypes/non_copy_data_types/seq_inner.rs
  protocols/v2/binary-sv2/codec/src/lib.rs
  protocols/v2/codec-sv2/Cargo.toml
  protocols/v2/noise-sv2/src/handshake.rs
  protocols/v2/noise-sv2/src/lib.rs
  protocols/v2/noise-sv2/src/signature_message.rs
  protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
  protocols/v2/roles-logic-sv2/src/handlers/mod.rs
  protocols/v2/roles-logic-sv2/src/job_dispatcher.rs
  protocols/v2/roles-logic-sv2/src/parsers.rs
  protocols/v2/roles-logic-sv2/src/routing_logic.rs
  protocols/v2/roles-logic-sv2/src/utils.rs
  protocols/v2/subprotocols/common-messages/src/setup_connection.rs
  protocols/v2/subprotocols/mining/src/lib.rs
  protocols/v2/subprotocols/mining/src/new_mining_job.rs
  protocols/v2/subprotocols/mining/src/open_channel.rs
  protocols/v2/subprotocols/mining/src/submit_shares.rs
  protocols/v2/subprotocols/template-distribution/src/new_template.rs
  protocols/v2/subprotocols/template-distribution/src/request_transaction_data.rs
  protocols/v2/subprotocols/template-distribution/src/set_new_prev_hash.rs
  protocols/v2/subprotocols/template-distribution/src/submit_solution.rs
  protocols/v2/sv2-ffi/src/lib.rs
  roles/jd-client/src/lib/error.rs
  roles/jd-client/src/lib/job_declarator/message_handler.rs
  roles/jd-server/src/lib/mod.rs
  roles/pool/src/lib/mining_pool/mod.rs
  roles/tests-integration/tests/sniffer_integration.rs
  roles/tests-integration/tests/translator_integration.rs
  roles/translator/src/lib/error.rs
  scripts/rust/clippy.sh
Labels: ready-to-be-merged

#1527 Prevent TP from immediately failing
  roles/tests-integration/lib/template_provider.rs
Labels: ready-to-be-merged

#1528 refactor: update dependencies for bip32 key derivation util
  utils/Cargo.lock
  utils/bip32-key-derivation/Cargo.toml
  utils/bip32-key-derivation/src/lib.rs
  utils/bip32-key-derivation/src/main.rs
Labels: ready-to-be-merged

#1510 sniffer block from message
  roles/tests-integration/lib/mod.rs
  roles/tests-integration/lib/sniffer.rs
  roles/tests-integration/tests/sniffer_integration.rs
Labels: ready-to-be-merged

#1530 add `RUST_BACKTRACE=1` on Integration Tests CI
  .github/workflows/integration-tests.yaml
Labels: integration-tests

#1501 Variable pool shares per min
  roles/pool/config-examples/pool-config-hosted-tp-example.toml
  roles/pool/config-examples/pool-config-local-tp-example.toml
  roles/pool/src/lib/config.rs
  roles/pool/src/lib/mining_pool/mod.rs
  roles/pool/src/lib/mod.rs
  roles/tests-integration/lib/mod.rs
  test/config/pool-mock-tp.toml
  test/config/sv1-test/pool-config.toml
Labels: sv2 pool, feature-request, blocker, adopter-feedback

#1535 Manage aritmetic overflow in `hashrate_from_target`
  protocols/v2/roles-logic-sv2/src/utils.rs
  roles/translator/src/lib/downstream_sv1/diff_management.rs
Labels: ready-to-be-merged

#1533 Organise deps in integration-tests crate
  roles/Cargo.lock
  roles/tests-integration/Cargo.toml
  roles/tests-integration/lib/mod.rs
Labels: ready-to-be-merged

#1555 add tracing to all IT test
  roles/tests-integration/tests/jd_integration.rs
  roles/tests-integration/tests/pool_integration.rs
  roles/tests-integration/tests/sniffer_integration.rs
Labels: ready-to-be-merged

#1518 Remove `stratum_common::url`
  common/src/lib.rs
  roles/jd-server/src/lib/config.rs
  roles/jd-server/src/lib/mempool/mod.rs
  roles/jd-server/src/lib/mod.rs
  roles/jd-server/src/main.rs
  roles/roles-utils/rpc/src/lib.rs
  roles/roles-utils/rpc/src/mini_rpc_client.rs
  roles/tests-integration/lib/mod.rs
Labels: ready-to-be-merged

#1589 Add IT checks in workflow and ignore workflow skipped test
  .github/workflows/fmt.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/rust-msrv.yaml
  scripts/rust/clippy.sh
  test/integration-tests/Cargo.lock
  test/integration-tests/lib/mod.rs
  test/integration-tests/lib/sniffer.rs
  test/integration-tests/tests/jd_integration.rs
  test/integration-tests/tests/jdc_fallback.rs
  test/integration-tests/tests/pool_integration.rs
  test/integration-tests/tests/sniffer_integration.rs
  test/integration-tests/tests/translator_integration.rs
Labels: ready-to-be-merged

#1537 `additional_coinbase_script_data` as part of `extranonce_prefix`
  protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
  protocols/v2/roles-logic-sv2/src/errors.rs
  protocols/v2/roles-logic-sv2/src/job_creator.rs
  protocols/v2/roles-logic-sv2/src/job_dispatcher.rs
  protocols/v2/subprotocols/mining/src/lib.rs
  roles/jd-client/config-examples/jdc-config-hosted-example.toml
  roles/jd-client/config-examples/jdc-config-local-example.toml
  roles/jd-client/src/lib/config.rs
  roles/jd-client/src/lib/downstream.rs
  roles/jd-client/src/lib/job_declarator/mod.rs
  roles/jd-client/src/lib/mod.rs
  roles/jd-client/src/lib/upstream_sv2/upstream.rs
  roles/mining-proxy/src/lib/upstream_mining.rs
  roles/pool/config-examples/pool-config-hosted-tp-example.toml
  roles/pool/config-examples/pool-config-local-tp-example.toml
  roles/pool/src/lib/mining_pool/mod.rs
  roles/translator/config-examples/tproxy-config-hosted-pool-example.toml
  roles/translator/config-examples/tproxy-config-local-jdc-example.toml
  roles/translator/config-examples/tproxy-config-local-pool-example.toml
  roles/translator/src/lib/proxy/bridge.rs
  roles/translator/src/lib/upstream_sv2/upstream.rs
  test/config/jds-stack-overflow/jdc-config.toml
  test/config/jds-stack-overflow/pool-config.toml
  test/config/pool-config-sri-tp-different-port.toml
  test/config/pool-config-sri-tp.toml
  test/config/pool-mock-tp-bad-coinbase.toml
  test/config/pool-mock-tp-bad-config.toml
  test/config/pool-mock-tp-standard-coverage.toml
  test/config/pool-mock-tp.toml
  test/config/sv1-test/pool-config.toml
  test/config/tproxy-config-no-jd-sv1-cpu-md.toml
  test/integration-tests/lib/mod.rs
Labels: sv2 pool, refactor, job-declarator-client, protocols
